### ISSUE TITLE
Example on readme doesn't actually work

### ISSUE THREAD

**Issue by WreckedAvent** [chrisdavies/eev#3]
Input:

```javascript
var e = new Eev()
function myHandler (data) { console.log(data); }

e.on('some-event', myHandler);
e.emit('some-event', { foo: 'Bar' });
```

Expected:
`{ foo: 'Bar' }` is passed to `myHander`

Actual:
Nothing happens.

Notes:
If `some-event` is changed to `some_event` or `someevent`, then it works. If this is intentional, it should probably be documented somewhere.

**Comment by chrisdavies** [comment]
Ah. Good find. I fixed it/added a test.
