### ISSUE TITLE
Event bus on window ?

### ISSUE THREAD

**Issue by abelkbil** [chrisdavies/eev#7]
Can use event-bus placed in browser's window. [as mentioned here](https://github.com/arkency/event-bus#global-event-bus-using-window-as-a-sharing-mechanism), the scope is if I have multiple independent application as a [Single-spa](https://github.com/CanopyTax/single-spa) Application.

Thank You

**Comment by chrisdavies** [comment]
I'm not sure what you're asking. You could use eev as an event bus if you wanted, yes. It's a generic event emitter and subscriber library.

**Comment by abelkbil** [comment]
@chrisdavies thanks
