### ISSUE TITLE
How to import this with angular 4 app 

### ISSUE THREAD

**Issue by debayanMuvi** [chrisdavies/eev#9]
Hi,

I am trying to make two Angular apps and i want an event emitter to listen events commonly in between two different application just like micro frontend but i am unable to import this in angular 4 . Can please give some instruction to integrate this.

**Comment by chrisdavies** [comment]
I'm not super familiar with Angular, but it's just JavaScript / TypeScript, so you should be able to import this library using an import statement:

`import Eev from "eev;`

Or you might have to do this:

`import * as Eev from "eev";`

I've had to do the latter in TypeScript when importing other libraries. (I've never tried importing Eev via TypeScript, though.)
